### ISSUE TITLE
Suggestion: Global member search sort and filter

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#16]
1.I think it would be a great update if the advance members plugin allowed you to set a global sorting and filtering for the members menu. That way it could be set for any community based on what their most important goals are for searching.

2. When you press the magnifying glass, it should automatically open the filter.

**Comment by ShivaniSEAO** [comment]
Hi @jhayden2000 ,

1. We are sorry but we didn't exactly understand your point. It would be great if you can please elaborate this a bit more for better clarification.

2. We are already working on improving the Search Functionality in our app and we may look into the possibilities to implement your suggestion in the apps in future.
