### ISSUE TITLE
Update the Members Section of mobile app

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#2]
Hello. This is a thread to talk about the lacking functionality of the Members menu and how to improve it.

1. Bring the filter button to the root members page
2. Members thumbnails should also display their location, age, and gender
3. The members list should be the members that are closest to you by default
4. the map feature, should show you people close to your location. currently, when i click on the map feature button, it brings me to China, and i have to move the map to my current location.

These 4 changes i think will go a long way into make the members search functionality alot more user friendly.

**Comment by ShivaniSEAO** [comment]
Hello @jhayden2000 ,

Thanks for providing your suggestions. All the above points (except display age and gender along with the thumbnails on Members Page) are added in the Roadmap and will be implemented in near future release.

**Comment by jhayden2000** [comment]
Thx Shivani. It would be nice to get the age and gender added to the thumbnails. Alot of communities are built for dating, and that makes life easier! Do you guys have an ETA for these changes?

**Comment by ShivaniSEAO** [comment]
Hi @jhayden2000 , 

1. It would be great if you can share a mock-up for Browse Members Page with us. We can have a look and may consider it for implementing in Mobile Apps.

2. It may take 6 weeks or less to release these enhancements in the Android Mobile App.

**Comment by wdag73** [comment]
@ShivaniSEAO ... This post was Three Months ago and you said less then 6 weeks? ... When is this going to be released?

**Comment by ShivaniSEAO** [comment]
Members section has been improved in both iOS and Android Mobile Apps.
