### ISSUE TITLE
Stories plugin bugs and suggestions

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#20]
1. When I add a second story, the new story should go to the front of the line, not the back.

2. When I record video stories, there is this weird still image that comes before it. Check my story out and see for yourself.

3. There should be a add story button on the home page

4. No effect filters and typing on a story makes this very bland.. these are important features.

5. You cant swipe left and right when in story mode to go to the next story.

number 1, 3  and 5, really should be a requirement before you guys sell this. This is basic functionality for stories on FB and IG

** number 4 is the most important thing on this list! this is the difference from you being able to sell this plugin for $50 or $150. I let a tester check the functions about and she was totally uninterested if she cant edit the photos with filters, effect or typing. **Without it, its not really stories.**

**Comment by ShivaniSEAO** [comment]
Hello @jhayden2000 ,

Thanks for providing your feedback on Stories Feature. We had gone through your suggested points and already taken many of them into consideration. You can test Stories Feature in Live Demo Android Mobile App to verify.
