### ISSUE TITLE
Bug: iPhone videos keep playing when you back out the video page

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#21]
here is a video of what im talking about. as you can see the video is uploaded and if i click on the back button i still hear the video playing.

https://drive.google.com/file/d/1GjXvfEeZg6kX0n4L3lXprSxYF3rvkTLO/view?usp=sharing

**Comment by pujabigstep** [comment]
Hello @jhayden2000 ,

We were able to replicate this issue in Demo App and we will resolve it in near future upgrade of the app.

**Comment by ShivaniSEAO** [comment]
Hi @jhayden2000 ,

This issue have been resolved and working fine in Live iOS App. Please verify and feel free to open this issue again in case if you'll have any further concerns or comments.

**Comment by jhayden2000** [comment]
i see that. only problem is you can only use that field once when creating the event. you cant edit it after you have created it.
