### ISSUE TITLE
iPhone gifs not working correctly after the new update

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#23]
hello team, i have a video here for you to see what happened when i was checking out the new iphone update.

This is on an iPhone 8 with the lastest OS update.

https://drive.google.com/file/d/1QdJ5sYYoE_tbncNPrvUAWNaAyCDW8hT_/view?usp=sharing

**Comment by SEAO-MobileApps** [comment]
This issue has been resolved.
