### ISSUE TITLE
Greeting X button color change

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#24]
This is a minor tweaks, but can you make the x black? It needs to be more visible.

![screenshot_20180514-142043_socialengine](https://user-images.githubusercontent.com/20259022/40015783-6a8e8806-5782-11e8-90e1-f6eed57139f4.jpg)

**Comment by ShivaniSEAO** [comment]
Hi Kahil Cross icon in Black Color won't go with the app. We have used grey color for icons, separators etc. across the app.
