### ISSUE TITLE
Issue: Menu Profile Banner - Stretched, loss of dimension.

### ISSUE THREAD

**Issue by LuisUrquilla** [BigStepTechnologies/SocialEngineAddOns-MobileApps#26]
### Platform and specifications (iOS, Android, Device Name, OS version)
1. iOS 
 

### Steps to reproduce
1. Check your Menu's Profile Banner
![profile banner](https://user-images.githubusercontent.com/39282735/40027264-39d26992-57a7-11e8-840f-cbe8b6791d08.PNG)

### Expected result
1. Proportionally sized profile background banner.

### Actual result
1. Profile banner is stretched horizontally.

**Comment by ShivaniSEAO** [comment]
Hello @LuisUrquilla ,

We were able to replicate this issue in Demo App and we will resolve it in near future upgrade of the app.

**Comment by ShivaniSEAO** [comment]
Hi @LuisUrquilla  ,

This issue have been resolved and working fine in Live iOS App. Please verify and open this issue again in case if you'll have any further concerns or comments.
