### ISSUE TITLE
Advanced events overview field needed

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#30]
Hello. The description field in "create an event" page always gives us problems when we are copy and pasting something into it. We would much rather use the overview field which is rich text. Is this possible to add to the create event options?

**Comment by ShivaniSEAO** [comment]
Hello @jhayden2000 ,

We would like to bring in your kind knowledge that we do have a separate field for "Overview" with a "Rich Text Editor". When you complete Event Creation Form and hit "Create Event" button, you will be redirected to a new page where you can add "Overview" for that Event.

You can cross-verify at your end and confirm.
