### ISSUE TITLE
Issue: Activty Feed - Liking a Post Affects Video Thumbnails 

### ISSUE THREAD

**Issue by LuisUrquilla** [BigStepTechnologies/SocialEngineAddOns-MobileApps#31]
### Platform and specifications (iOS, Android, Device Name, OS version)
1.  iOS
 

### Steps to reproduce
1.  While video thumbnails are visible on the activity feed, proceed to like a non-video post.

### Expected result
1.  The non-video post should simply receive a like.

### Actual result
1. The non video post receives a like but thumbnail of video post(s) disappear.  All you see is a white thumbnail with a Play icon in the middle.

**Comment by LuisUrquilla** [comment]
Update:  tested on Android, this is an iOS issue only.

**Comment by ShivaniSEAO** [comment]
@LuisUrquilla It would be great if you can please share a screenshot for this issue.

**Comment by LuisUrquilla** [comment]
![feed](https://user-images.githubusercontent.com/39282735/40125777-bb718de0-58f9-11e8-8e79-e187259ff572.PNG)

**Comment by SEAO-MobileApps** [comment]
Hi @LuisUrquilla 
This Issue fixed in previous Releases, please let us know if there's anything further apart from this.
