### ISSUE TITLE
Issue: Comments - Unable to Edit Inner Characters in Comment 

### ISSUE THREAD

**Issue by LuisUrquilla** [BigStepTechnologies/SocialEngineAddOns-MobileApps#32]
### Platform and specifications (iOS, Android, Device Name, OS version)
1. iOS
 

### Steps to reproduce
1. Post a sentence with 5 words
2. Edit the post and try to edit word #2
3. As soon as you type one character the cursor repositions automatically at the end of the sentence.

### Expected result
1. Should be able to edit any character between the first and last word.

### Actual result
1.  As soon as you type one character the cursor reposition automatically to the end of the entire sentence.

**Comment by ShivaniSEAO** [comment]
@LuisUrquilla Thanks for reporting this issue. Do you mean that:

Suppose you wrote "Hey, how are you doing ?" from Status Box
Now, when you try to edit "how" in feed, the cursor goes to the end of sentence i.e. at the end of phrase "doing" ?

Please confirm. If I got you wrong, then please explain us with an example.

**Comment by LuisUrquilla** [comment]
That is correct, the cursor will always immediately jump to the end of the sentence, making it difficult to edit the comment.

**Comment by jhayden2000** [comment]
tested, i also get this issue

**Comment by PapasFritasUSA** [comment]
@ShivaniSEAO  I think this is not fixed yet, this bug so bother me. i think this is very big major bug nwo

check this bug: 

https://1drv.ms/v/s!AmNA-VwAFMdjguM79GVXujYsjPXnkQ.

I am using onedrive from microsoft, so it is safe open and watch it 

thank you

**Comment by ShivaniSEAO** [comment]
Hi @jhayden2000 , @LuisUrquilla @PapasFritasUSA 

This issue have been resolved and working fine in Live iOS App. Please verify and open this issue again in case if you'll have any further concerns or comments.
