### ISSUE TITLE
Bug: videos posting gives an error

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#34]
This is on iPhone

![img_0056](https://user-images.githubusercontent.com/20259022/40260778-8fc92086-5aca-11e8-8b3e-44b9d0089abf.png)
![img_0058](https://user-images.githubusercontent.com/20259022/40260779-8fd84778-5aca-11e8-94cd-6d85fb5e9735.png)
![img_0060](https://user-images.githubusercontent.com/20259022/40260780-8fe6354a-5aca-11e8-8109-a4b5a1e4da48.png)

**Comment by ShivaniSEAO** [comment]
Hello @jhayden2000 ,

We have checked this issue by uploading Videos in multiple devices in iOS Mobile App and Video Uploading is working fine in the app. Please verify the issue and confirm so, we can close the issue.

**Comment by jhayden2000** [comment]
im no longer seeing this issue.
