### ISSUE TITLE
bug: iPhone app has a delay when liking comments

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#35]
### Platform and specifications (iOS, Android, Device Name, OS version)
1.  IOS

Its intermittent but im sure others get this issue as well.

https://drive.google.com/file/d/1sK5Ghzq4aMSyTF_xWp8-nL4rjh6nfihC/view?usp=sharing

**Comment by jhayden2000** [comment]
here is another. 

https://drive.google.com/file/d/1HsF2nINa_BlVy1FU2d71cNG1EL_ZilgB/view?usp=sharing

**Comment by SEAO-MobileApps** [comment]
Hello @jhayden2000,

We were able to replicate this issue in Demo App and we will resolve it in near future upgrade of the app.

**Comment by ShivaniSEAO** [comment]
Hi @jhayden2000 ,

This issue have been resolved and working fine in Live iOS App. Please verify and open this issue again in case if you'll have any further concerns or comments.
