### ISSUE TITLE
BUG: iPhone false notification count. Please fix!!

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#36]
### Platform and specifications (iOS, Android, Device Name, OS version)
1. IOS
 

If there is one thing that my iphone customers hate, its the notification system. Mainly because their count is never accurate: the App icon will say one number, while the notification button onside the app will say another, and the notification list will show a different amount.

![img_0064](https://user-images.githubusercontent.com/20259022/40261730-68112812-5ad0-11e8-9b8b-1d196bd386b1.jpg)
![img_0065](https://user-images.githubusercontent.com/20259022/40261731-682308b6-5ad0-11e8-9f90-79aa9d71388e.jpg)

**Comment by LuisUrquilla** [comment]
Yeah, that drives me in sane.  It’s been an ever lasting issue.

**Comment by PapasFritasUSA** [comment]
I have this problem too, seao Need to fix this problem asap

**Comment by jhayden2000** [comment]
It would be nice if you ould make a "mark as read" button like the website does, so we can clear the notifications

**Comment by ShivaniSEAO** [comment]
Hi @jhayden2000 , @LuisUrquilla @PapasFritasUSA 

This issue have been resolved and working fine in Live iOS App. Please verify and feel free to open this issue again in case if you'll have any further concerns or comments.

**Comment by PapasFritasUSA** [comment]
Did not fix anything? I create another issue already.

**Comment by PapasFritasUSA** [comment]
@SEAO-MobileApps  @ShivaniSEAO  @bigsteptech 

Latest version i already update two time now at apple store:

https://1drv.ms/u/s!AmNA-VwAFMdjgvsLTTVNLEgG1NdvVg

Bug  
https://github.com/BigStepTechnologies/SocialEngineAddOns-MobileApps/issues/53

**Comment by PapasFritasUSA** [comment]
I did repost:

https://github.com/BigStepTechnologies/SocialEngineAddOns-MobileApps/issues/53
