### ISSUE TITLE
"feelings" not showing on iPhone app

### ISSUE THREAD

**Issue by ghost** [BigStepTechnologies/SocialEngineAddOns-MobileApps#37]
### Platform and specifications (iOS, Android, Device Name, OS version)
1.  iOS

### Steps to reproduce
1.  Posted update on Mobile demo (via desktop) using the "feeling" feature.

### Expected result
1. To see the same "feeling" feature shown on the iPhone app.

### Actual result
1.  The post shows on the iphone but without the feeling.
![screen shot 2018-06-14 at 20 42 06](https://user-images.githubusercontent.com/40277625/41434500-e04d6590-7013-11e8-86f2-6501c55650fb.png)

**Comment by ShivaniSEAO** [comment]
Hello Russel,

"Feelings and Activity" feature is not yet implemented in iOS Mobile App. Rest all new features of Advanced Activity Feeds, except Feelings & Activity and Stickers, will be released in our demo iOS Mobile App by early next week.
