### ISSUE TITLE
Suggestion: make photo comments larger or clickable

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#4]
One big issue I see with photo comments is that they display very small in most cases but it's sporadic. They need to have either a default size that they all display in that is easily viewable or they need to be clickable so you can see a full screen version
![screenshot_20180405-091649](https://user-images.githubusercontent.com/20259022/38367984-185b32ee-38b2-11e8-9807-4bb641b77a54.jpg)

**Comment by ShivaniSEAO** [comment]
@jhayden2000 We have accepted your suggestion and will implement it in our Android Mobile App in near future release.

**Comment by ShivaniSEAO** [comment]
It has been implemented in both iOS and Android Mobile Apps.
