### ISSUE TITLE
Verify option not showing for all users

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#5]
Testing this on an Android Galaxy Note 8
I go to random user profiles
The verification options doesn't show up for all of them
![screenshot_20180405-162228](https://user-images.githubusercontent.com/20259022/38389914-c886b27a-38ed-11e8-9c13-c2fdbb863d86.jpg)
![screenshot_20180405-162211](https://user-images.githubusercontent.com/20259022/38389915-c89f136a-38ed-11e8-9afe-c8e8597e0efd.jpg)
![screenshot_20180405-162158](https://user-images.githubusercontent.com/20259022/38389916-c8b64d5a-38ed-11e8-98cd-3f9bf28c9fcd.jpg)

**Comment by ShivaniSEAO** [comment]
@jhayden2000 It was because of the Member Level Based Settings, but we have now changed the settings. Please check this again and confirm if it's working fine at your end.

Additionally, we would appreciate if you can please assign new issues by following a defined template.

**Comment by jhayden2000** [comment]
i still dont see it on my Kahil Carlson account on Android or my Paul Shaual account on iPhone

**Comment by ShivaniSEAO** [comment]
Please share your account login details at apps@socialengineaddons.com and user's name for which you are not able to see Verify option.

**Comment by ShivaniSEAO** [comment]
Hello @jhayden2000,

If you are still facing this issue, then please provide us above requested account details. Else, we can close this issue.

**Comment by jhayden2000** [comment]
its working. thanks.
