### ISSUE TITLE
Ios comment error

### ISSUE THREAD

**Issue by PapasFritasUSA** [BigStepTechnologies/SocialEngineAddOns-MobileApps#51]
When i comment and click sent button, i got error. 

You need to post more comment that error will show.

When you write like said 12 more word, it will show this errors when you ready to post, it will erase what did you wrote.  

https://1drv.ms/u/s!AmNA-VwAFMdjgvsG3FmZRbtqQ-OLOg

**Comment by SEAO-MobileApps** [comment]
Hi @PapasFritasUSA

We tried Replicating this bug on the same feed as shown in the screenshot but it is not Replicating on our End.
