### ISSUE TITLE
Notification Count still did not fix it

### ISSUE THREAD

**Issue by PapasFritasUSA** [BigStepTechnologies/SocialEngineAddOns-MobileApps#53]
OS: IOS
phone: X
Version:11.4.1

Show one count notificaiton in app, but app icon  show count for 8. What is going on? 

https://1drv.ms/f/s!AmNA-VwAFMdjgvsHBQIpnAJCsGKFLw

Test it before share to other people

**Comment by PapasFritasUSA** [comment]
i am very disappoint and you guy dismiss/ignore  this issue, also close bug.

**Comment by PapasFritasUSA** [comment]
@SEAO-MobileApps  @ShivaniSEAO  @bigsteptech

**Comment by PapasFritasUSA** [comment]
This video show this error

https://1drv.ms/v/s!AmNA-VwAFMdjgvsrJL-D4JC8RbdHxA

Show 15 app icon badge 

And inside the app show only one notification icon

**Comment by SEAO-MobileApps** [comment]
Duplicate issue of Git Id -> 

https://github.com/BigStepTechnologies/SocialEngineAddOns-MobileApps/issues/52
