### ISSUE TITLE
iOS App Release 2.5.6 - Feedback

### ISSUE THREAD

**Issue by ShivaniSEAO** [BigStepTechnologies/SocialEngineAddOns-MobileApps#54]
- [ ] Auto-suggest Search Results
- [ ] Login Screen - New Interface
- [ ] Store and Product Creation
- [ ] On-the-spot Video Playing in Activity Feeds
- [ ] New Material Design based App Slideshow
- [ ] App Tour / App Walk Through
- [ ] Location Auto-detection
- [ ] Map View in Multiple Listing Types and Members Page
- [ ] Two View Types on Multiple Listing Types Module Browse Pages
- [ ] Two View Types on Members Browse Pages
- [ ] Integrated Events Extension with all SocialEngineAddOns Modules
- [ ] Other Important UI Enhancements
- [ ] Important Bug Fixes across the App

**Comment by LuisUrquilla** [comment]
Hi Shivani, 

The update looks great, I haven't found major issues yet. The only issue I found with Ratings/reviews I already reported just a few minutes ago.

The app is looking awesome, please keep up the great work.

Thanks.
