### ISSUE TITLE
Android & iOS Issue - Page Reviews Lost After Edit

### ISSUE THREAD

**Issue by LuisUrquilla** [BigStepTechnologies/SocialEngineAddOns-MobileApps#55]
### Platform and specifications (iOS, Android, Device Name, OS version)
1. 
iOS12.0, iPhone7
Android 8.0.0, Galaxy S7
 

### Steps to reproduce
1. Create a page review on iOS
2. Now edit review on Android, you'll notice there are no star rating available to adjust, only review questions.
3. Make changes to questions and save.

### Expected result
1. For updated review/rating to have updated.

### Actual result
1. Entire review is wiped on both iOS and Android.

**Comment by SEAO-MobileApps** [comment]
Hi @LuisUrquilla

We tried Replicating this but it didn't Replicate on our end.

If this bug specifically exists in your app then please file a support ticket at apps@socialengineaddons.com
