### ISSUE TITLE
Map looks compressed in feeds in iOS App

### ISSUE THREAD

**Issue by ShivaniSEAO** [BigStepTechnologies/SocialEngineAddOns-MobileApps#59]
### Platform and specifications (iOS, Android, Device Name, OS version)
1. iOS
 

### Steps to reproduce
1. Go to Activity Feeds > Check-in > Feed with the map will get generated > map in feed looks a bit compressed

### Expected result
1. Map should not look compressed like Android.

### Actual result
1. Map looks a bit compressed

### Screenshot:
![89768](https://user-images.githubusercontent.com/11085507/52120352-08de6380-2642-11e9-83e9-b0fe1c1750b5.jpg)

**Comment by yogesh-kumar-gupta-bs** [comment]
Issue resolved

**Comment by ShivaniSEAO** [comment]
Issue resolved and can be verified from Live Demo App.
