### ISSUE TITLE
Cant do multiple Scheduled posts

### ISSUE THREAD

**Issue by jhayden2000** [BigStepTechnologies/SocialEngineAddOns-MobileApps#7]
We tried to do multiple Scheduled posts. Set 3 at different times and once we did that all three posts were posted immediately.

![screenshot_20180407-152356](https://user-images.githubusercontent.com/20259022/38459562-28f09e50-3a79-11e8-9c8b-00e69dd9fee2.jpg)

**Comment by ShivaniSEAO** [comment]
Hello @jhayden2000 ,

Scheduled Posts are executed via Cron Job of Task Scheduler. So when a Cron Job runs, it process all the queued jobs at once. Thus, this is not an issue and it's behavior depends on the Time Limit you have set for Task Scheduler.

**Comment by jhayden2000** [comment]
Shivani. if you get a chance do this test and you will see what i mean.
Make a post and set the schedule for 15 minutes away
once you make the first post then immediately make a sond post and set it for 30 minutes away
then make a third set for 45 minutes away. 

you should see all of them immediately post instead of posting at their scheduled times
